package model;

import java.io.Serializable;

public class Answer implements Serializable {
	private static final long serialVersionUID = 8915759794416147509L; // auto-generated by serializable
	private String answer; // the answer itself
	private boolean isTrue; // is the answer correct

	public Answer(String answer, boolean isTrue) {
		this.answer = answer.trim();
		this.isTrue = isTrue;
	}

	public Answer(Answer answer) {
		this.answer = answer.getAnswer();
		this.isTrue = answer.getIsTrue();

	}

	public int getLength() {
		return answer.length();
	}

	public String getAnswer() {
		return answer;

	}

	public boolean setAnswer(String answer) {
		System.out.println("setanswer");
		answer = answer.trim();
		this.answer = answer;
		return true;
	}

	public boolean getIsTrue() {
		return isTrue;
	}

	public boolean setIsTrue(boolean isTrue) {
		this.isTrue = isTrue;
		return true;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Answer other = (Answer) obj;
		return (answer.compareToIgnoreCase(other.answer) == 0);
	}

	@Override
	public String toString() {
		return "Answer: " + answer + " | The answer is: " + (isTrue ? "" : "IN") + "CORRECT";
	}

}
