package model;

import java.io.Serializable;

public abstract class Question implements Serializable {

	private static final long serialVersionUID = -1285366845364926302L; // auto-generated by serializable
	protected static int idGen = 1000; // static id generator
	protected int serialNum; // question id
	protected String quest; // the question
	protected int answerLength; // used only while creating a test for sorting

	public Question(String quest) {
		setQuest(quest);
		this.serialNum = idGen++;
		this.answerLength = 0;
	}

	public abstract boolean setAnswerLength();

	public int getAnswerLength() {
		setAnswerLength();
		return answerLength;
	}

	public String getQuest() {
		return quest;
	}

	public boolean setQuest(String quest) { // change the question
		this.quest = quest.trim();
		return true;
	}

	public abstract boolean addAnswer(String answer, boolean isTrue) throws Exception;

	public abstract boolean removeAnswer(int answerIndex);

	public int getSerialNum() { // get question id
		return serialNum;
	}

	public abstract boolean isValid();

	public abstract String toStringForTest();

	@Override
	public abstract boolean equals(Object obj);

	@Override
	public abstract String toString();
}
